import:
    title: 'golem15.translate::lang.messages.import_messages_link'
    modelClass: Golem15\Translate\Models\MessageImport
    redirect: winter/translate/messages

export:
    title: 'golem15.translate::lang.messages.export_messages_link'
    modelClass: Golem15\Translate\Models\MessageExport
    redirect: winter/translate/messages
